version: '3'

services:
  go:
    build:
      context: .
      dockerfile: ./containers/go/Dockerfile
    ports:
      - 8080:8080
    command: "/main"
  next:
    build:
      context: .
      dockerfile: ./containers/nextjs/Dockerfile
    #tty: true
    volumes:
      - ./next:/nextjs
      - /nextjs/node_modules
      - /nextjs/.next
    ports:
      - 3000:3000
    entrypoint: "npm run dev"
    environment:
      - WATCHPACK_POLLING=true
