version: '3'

services:
  go:
    build:
      context: .
      dockerfile: ./containers/go/Dockerfile
    tty: true
    volumes:
      - ./go:/go/src
  next:
    build:
      context: .
      dockerfile: ./containers/nextjs/Dockerfile
    volumes:
      - ./next:/nextjs
      - ./go/compiled:/go
      - /nextjs/node_modules
      - /nextjs/.next
    ports:
      - 80:3000
    entrypoint: "npm run dev"
    environment:
      - WATCHPACK_POLLING=true
